name: Rust DB Setup and Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build project
        run: |
          cargo build --verbose

      - name: Test project
        run: |
          cargo test --verbose
          cargo test --verbose --no-default-features